package crazylimits.dragonfall.body;

import crazylimits.dragonfall.anim.DragonAnim;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Base64;
import java.util.EnumMap;
import java.util.Locale;
import java.util.Map;

/**
 * Where the model's hitbox anchors are on every animation frame (generated by {@code tools/parts.py}).
 *
 * <p>Points are in model space, in blocks: y up, the head toward -z, +x to the dragon's right. One frame
 * holds {@link #POINTS} points: first the {@link #PARTS} part anchors, then the {@link #NECK_PIVOTS}
 * neck pivots (neck_1..neck_4, head_group), then the {@link #TAIL_PIVOTS} tail pivots (tail_1..tail_9),
 * then from {@link #FRAME_START}: the left shoulder's pivot and a point one block along its X axis, the
 * same for the right shoulder, the body's pivot, a point one block ahead of it and one block above it.
 * The tail is keyed straight: its points are where the body carries a straight tail ({@link TailChain}
 * bends it).
 */
public final class PoseTrack {
	public static final int PARTS = PoseData.PART_NAMES.length;
	public static final int NECK_PIVOTS = PoseData.NECK_PIVOTS, TAIL_PIVOTS = PoseData.TAIL_PIVOTS;
	public static final int NECK_START = PARTS, TAIL_START = PARTS + NECK_PIVOTS;
	public static final int FRAME_START = TAIL_START + TAIL_PIVOTS;
	public static final int LEFT_SHOULDER = FRAME_START, RIGHT_SHOULDER = FRAME_START + 2, BODY_AXIS = FRAME_START + 4;
	public static final int POINTS = FRAME_START + PoseData.FRAME_POINTS;
	/** Part chains: not on a chain, on the neck (head included), on the tail, on a wing. */
	public static final int CHAIN_NONE = 0, CHAIN_NECK = 1, CHAIN_TAIL = 2, CHAIN_LEFT_WING = 3, CHAIN_RIGHT_WING = 4;

	private record Track(float[] data, int frames, double step, double length, boolean loop) {}

	private static final Map<DragonAnim, Track> TRACKS = new EnumMap<>(DragonAnim.class);

	static {
		for (int i = 0; i < PoseData.ANIMS.length; i++) {
			DragonAnim anim = DragonAnim.valueOf(PoseData.ANIMS[i].toUpperCase(Locale.ROOT));
			ByteBuffer bytes = ByteBuffer.wrap(Base64.getDecoder().decode(PoseData.DATA[i])).order(ByteOrder.LITTLE_ENDIAN);
			float[] data = new float[bytes.remaining() / 2];
			for (int k = 0; k < data.length; k++) data[k] = bytes.getShort() / 256.0F;
			TRACKS.put(anim, new Track(data, PoseData.FRAMES[i], PoseData.STEP[i], PoseData.LENGTH[i], PoseData.LOOP[i]));
		}
		for (DragonAnim anim : DragonAnim.values()) {
			if (!TRACKS.containsKey(anim)) throw new IllegalStateException("No pose track for " + anim + "; rerun tools/build_assets.py");
		}
	}

	private PoseTrack() {}

	public static String partName(int part) {
		return PoseData.PART_NAMES[part];
	}

	public static float partWidth(int part) {
		return PoseData.PART_WIDTH[part];
	}

	public static float partHeight(int part) {
		return PoseData.PART_HEIGHT[part];
	}

	/** {@link #CHAIN_NONE}, {@link #CHAIN_NECK}, {@link #CHAIN_TAIL}, {@link #CHAIN_LEFT_WING} or {@link #CHAIN_RIGHT_WING}. */
	public static int partChain(int part) {
		return PoseData.PART_CHAIN[part];
	}

	/** How many segments of its chain the part hangs below (5 on the neck = the head). */
	public static int partDepth(int part) {
		return PoseData.PART_DEPTH[part];
	}

	/** Length of the animation in seconds. */
	public static double length(DragonAnim anim) {
		return TRACKS.get(anim).length;
	}

	/**
	 * Fills {@code out} ({@link #POINTS} * 3) with the frame at {@code seconds}: looping animations wrap,
	 * the others hold their last frame. Frames are linearly interpolated.
	 */
	public static void sample(DragonAnim anim, double seconds, double[] out) {
		Track track = TRACKS.get(anim);
		double t = track.loop ? seconds - Math.floor(seconds / track.length) * track.length : Math.max(0.0, Math.min(track.length, seconds));
		double f = t / track.step;
		int a = Math.min(track.frames - 1, (int) Math.floor(f));
		int b = Math.min(track.frames - 1, a + 1);
		double k = Math.min(1.0, f - a);
		int stride = POINTS * 3;
		for (int i = 0; i < stride; i++) {
			double va = track.data[a * stride + i], vb = track.data[b * stride + i];
			out[i] = va + (vb - va) * k;
		}
	}
}
