modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''${description}'''
authors = "${authors}"
${iconKey} = "assets/dragonsworn/icon.png"

[[mixins]]
config = "dragonsworn.mixins.json"

[[mixins]]
config = "dragonsworn.breath.mixins.json"

[[mixins]]
config = "dragonsworn.arena.mixins.json"

# Iron's Spells 'n Spellbooks: its Dragon's Breath spell breathes void flame (inert without it)
[[mixins]]
config = "dragonsworn.irons.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${mcVersion}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "geckolib"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${id}]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange = "[3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "cloth_config"
type = "optional"
versionRange = "[15,)"
ordering = "NONE"
side = "CLIENT"
