modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''${description}'''
authors = "crazylimits"

[[mixins]]
config = "dragonfall.mixins.json"

[[mixins]]
config = "dragonfall.breath.mixins.json"

[[mixins]]
config = "dragonfall.arena.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${mcVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "geckolib"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"
